---
- name: Apply Kubernetes namespace
  kubernetes.core.k8s:
    state: present
    src: /mnt/Cracows/depi/projects/my_own_prj/k8s/ns.yml
    kubeconfig: /home/tarek/.kube/config

- name: Apply Kubernetes configmap
  kubernetes.core.k8s:
    state: present
    src: /mnt/Cracows/depi/projects/my_own_prj/k8s/cf.yml
    kubeconfig: /home/tarek/.kube/config
  notify:
    - Restart self-app-dep


- name: Apply Kubernetes deployment
  kubernetes.core.k8s:
    state: present
    src: /mnt/Cracows/depi/projects/my_own_prj/k8s/dep.yml
    kubeconfig: /home/tarek/.kube/config

- name: Apply Kubernetes service
  kubernetes.core.k8s:
    state: present
    src: /mnt/Cracows/depi/projects/my_own_prj/k8s/serv.yml
    kubeconfig: /home/tarek/.kube/config

- name: Get all resources in the namespace
  command: kubectl get all -n "{{ namespace }}" --kubeconfig=/home/tarek/.kube/config
  register: kubectl_output
  changed_when: false

- name: Show all resources output
  debug:
    var: kubectl_output.stdout

- name: Get Service NodePort
  command: kubectl get svc {{ service_name }} -n {{ namespace }} -o=jsonpath='{.spec.ports[0].nodePort}' --kubeconfig=/home/tarek/.kube/config
  register: service_port

- name: Display Service NodePort
  debug:
    msg: "Service '{{ service_name }}' is exposed on port: {{ service_port.stdout }}"

- name: Display Service Access URL
  debug:
    msg: "Access the service at: http://192.168.49.2:{{ service_port.stdout }}"
